default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: marine_portal_development

test:
  <<: *default
  database: marine_portal_test

production:
  <<: *default
  database: marine_portal_production
  username: marineportal
  password: conserveworld
  host: localhost
