default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paperclip:
    attachment_url: "/pdfs/:id/:filename"
    attachment_path: "/pdfs/:id/:filename"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

staging:
  <<: *default
